### ISSUE TITLE
Col-x with more than one class

### ISSUE THREAD

**Issue by eTomate** [KingPixil/wing#11]
It seems, like it's required to add additional classes behind the col-x class.
If you write a col-div this way:

```
<div class="myclass col-6">
Some content
</div>
```
the grid is destroyed and doesn't work as intended.

If you switch the classes everything works fine.
```
<div class="col-6 myclass">
Some content
</div>
```

BR

**Comment by KingPixil** [comment]
Thanks @eTomate 

This is a bug, nice catch! For now just use custom classes after `col-x`, and it should work fine. I don't know what is causing this, but I will try to figure it out :)

Thanks again :+1:

**Comment by eTomate** [comment]
I just submitted a bugfix for this problem.
The problem was the `[class^='col-]` selector for row. By adding a "*=' col-' selector, we catch col-x elements within a  list of classes.

**Comment by KingPixil** [comment]
@eTomate Thanks!

I merged the PR, the bug should be fixed now :+1:
