### ISSUE TITLE
Inverted Button Example Wrong Class

### ISSUE THREAD

**Issue by jondcoleman** [KingPixil/wing#14]
Example on the website says `<button class="btn btn-outline">outline-inverted</button>`

It should be `<button class="btn btn-outline-inverted">outline-inverted</button>`

**Comment by jondcoleman** [comment]
Didn't see a way to make PR against docs.

**Comment by KingPixil** [comment]
Haha, thanks for pointing that silly typo out @jondcoleman.

It's cool if you make a PR, sorry if I wasn't clear.

Thanks, I will fix this :+1:
