### ISSUE TITLE
Errors on Splash Page

### ISSUE THREAD

**Issue by Miserlou** [KingPixil/wing#16]
<img width="1009" alt="screen shot 2016-09-05 at 10 44 12 pm" src="https://cloud.githubusercontent.com/assets/139987/18260307/5e43e6d4-73ba-11e6-94be-32eed35f9e3b.png">
<img width="1009" alt="screen shot 2016-09-05 at 10 44 28 pm" src="https://cloud.githubusercontent.com/assets/139987/18260320/76753532-73ba-11e6-9dc6-9fed0b3db00c.png">

See bottom right

**Comment by KingPixil** [comment]
That's some weird behavior (in the first screenshot), most likely an issue with the font or your browser.

Mind telling me what browser this is?

Thanks for letting me know @Miserlou :+1:

**Comment by Miserlou** [comment]
OSX, Firefox 48. It only happens in one strip.

**Comment by KingPixil** [comment]
That's unusual, the second screenshot is partially fixed already, when the screen is resized to be smaller the footer and github buttons will go to the bottom.

But the font getting cut off is a little weird, any theories?

I will look into this tomorrow, as I have to sleep :zzz: right now.

**Comment by KingPixil** [comment]
Figured it out, its an issue with Firefox rendering a font, nothing I can do.
