### ISSUE TITLE
Example Section

### ISSUE THREAD

**Issue by KingPixil** [KingPixil/wing#2]
If you guys use Wing in your projects, send me the link by commenting below.

Please use the format of
**Name - (http://link.com) - Description**

 I will make an examples section of people using Wing!

**Comment by FootballCoder** [comment]
http://www.yearofcode.ml/

**Comment by FootballCoder** [comment]
Year Of Code - (http://www.yearofcode.ml/) - Making one program every day for a year.

**Comment by akaankshr4j** [comment]
Project61 (http://goo.gl/43PEFN) A collection of 61 projects made to learn coding better

**Comment by KingPixil** [comment]
Doesn't seem to use Wing at the moment...

**Comment by akaankshr4j** [comment]
Hey @KingPixil I've just updated the repo + site and its using wing.

**Comment by KingPixil** [comment]
Cool, I will add it now @akaankshr4j  :smile:

**Comment by KingPixil** [comment]
I'll close this for now, just tweet at me if you use/like Wing 😄
