### ISSUE TITLE
Fix non-standard property

### ISSUE THREAD

**Issue by Kcchouette** [KingPixil/wing#23]
Thank you very much for this good CSS framework.

I open this issue because I see that you use a lot of non-standard property for CSS3.0 (the _-moz_ and _-webkit_ property)
[Here a CSS validation from W3C](https://jigsaw.w3.org/css-validator/validator?uri=https%3A%2F%2Fcdn.rawgit.com%2FKingPixil%2Fwing%2Fmaster%2Fdist%2Fwing.css&profile=css3&usermedium=all&warning=1&vextwarning=&lang=en).

Can you fix it?
Moreover, this help to fix #10!

**Comment by KingPixil** [comment]
Hello @Kcchouette 

Glad you like Wing! Unfortunately, things like `-moz-` and `-webkit-` are needed.

They are warnings in W3C, but when a browser renders the CSS, it looks for those properties and marks them as experimental, to allow more things to support IE 9. Wing needs those prefixes to be able to support various browsers, but I will keep this open to bring out those errors.

Thanks!

**Comment by KingPixil** [comment]
The other properties will be added soon, it is safe to keep them.
