### ISSUE TITLE
Add .alert (or .message) class

### ISSUE THREAD

**Issue by Kcchouette** [KingPixil/wing#25]
Hello,

Is there a way to add `.alert` or `.message` at wing css?

For example, here a reference from Siimple CSS framework:
![Siimple CSS framework capture](https://cloud.githubusercontent.com/assets/3000936/19120583/89603d56-8b23-11e6-81a0-1dbee6b4f9c9.PNG)

**Comment by KingPixil** [comment]
Hey @Kcchouette!

Sadly, I probably will not add this, it's useful, but as you know, Wing's point is to be as useful as possible. I am thinking of adding plugins, and this can be one!

**Comment by Kcchouette** [comment]
@KingPixil : it can be a good idea, to add plugins. Because I think these messages box are very useful :)
