### ISSUE TITLE
Outlined buttons have different height

### ISSUE THREAD

**Issue by CodeBrauer** [KingPixil/wing#33]
If you use both buttons side by side they don't align perfect, because the outlined buttons has +6px of height.

![bildschirmfoto 2016-10-27 um 12 21 33](https://cloud.githubusercontent.com/assets/2059754/19763895/884465c2-9c40-11e6-81b7-e3c6f8cf4264.png)
![bildschirmfoto 2016-10-27 um 12 21 19](https://cloud.githubusercontent.com/assets/2059754/19763896/8849384a-9c40-11e6-97e1-09f71b48b989.png)

**Comment by talonbragg** [comment]
Just fix this with CSS and just change the width and the height back to normal. This is extremely simple, I had this issue when I was using wing. I fixed it just like this, this is mainly a flaw with Kabir's CSS. Kabir if you are reading this, please fix it, it can be extremely annoying sometimes when you are using wing. It brings down the amount of people that use this.

**Comment by CodeBrauer** [comment]
@talonbragg - There is already a pending PR https://github.com/KingPixil/wing/pull/34
