### ISSUE TITLE
Not Working With Secure https

### ISSUE THREAD

**Issue by talonbragg** [KingPixil/wing#38]
I tried to link wing on to my https ssl lock secured site, and when it is on https, it won't work. It says hat it is an insecure stylesheet. I recommend that you get ssl for wing so that it is secure. I also did the same for https://custommarkup.ml, and it still won't work(Even though I don't want to use it, I was just testing it out). Thanks.

**Comment by Yinchie** [comment]
Download Wing CSS to your own host and link it directly from your own host? Problem solved.

**Comment by KingPixil** [comment]
As @Yinchie said, just add it to your own host, or use a CDN...
