### ISSUE TITLE
Additional Flexbox Components

### ISSUE THREAD

**Issue by wad3g** [KingPixil/wing#46]
I'm not sure what, if anymore, components/plugins you'd like added, but I've rolled a lot of my own flexbox layouts, cards, panels, etc..

Depending on what you'd like to add I could give a few of them a shot.

**Comment by KingPixil** [comment]
I think a card would be nice, just remember, keep it as minimal as possible :wink:

**Comment by KingPixil** [comment]
Not sure if we need any more of these, so I'm closing this for now. Let me know if anyone would like a new component.
