### ISSUE TITLE
Grids aren't working

### ISSUE THREAD

**Issue by kovirolik** [KingPixil/wing#50]
Grids aren't working :(
I have Wing included via unpkg.

**Comment by KingPixil** [comment]
Hey! Could you provide specifically what is not working?

**Comment by kovirolik** [comment]
Grids are just displayed as regular divs

**Comment by KingPixil** [comment]
It would be great if you could provide a [jsFiddle](https://jsfiddle.net) or something similar showing the issue, because right know, it is hard to tell what is going on.

**Comment by kovirolik** [comment]
https://jsfiddle.net/96pcg488/
Here is it

**Comment by kovirolik** [comment]
https://jsfiddle.net/bfo61j50/
here is it

**Comment by kovirolik** [comment]
I got it. It's error in docs. I'll send pull request.

**Comment by KingPixil** [comment]
Thanks! Fixed it 👍
