### ISSUE TITLE
'fixed' class but still in sequence (enhancement)

### ISSUE THREAD

**Issue by CLYeo** [KingPixil/wing#55]
hi,

I was thinking the 'fixed' class can be used for a floating top menu bar.
but it seems like it fixed to a specific position (usable for side menu).

it will be good if there is another class that is fixed but still in sequence in term of the row element of the grid - in the screenshot, Row 2 should be under FIXED TITLE.

(not sure if it's doable, I'm new to css)

![image](https://user-images.githubusercontent.com/29327709/27020665-c440e738-4f75-11e7-9475-79f4bedfce6a.png)

**Comment by KingPixil** [comment]
This can be done by toggling `position: fixed` on and off based on the screen size. You really shouldn't have a fixed row anyway, as it'll break the grid. Think about it, you want a row that is supposed to have a set position in the grid to be fixed onto a certain position.

[Here is](https://jsfiddle.net/uLg97090/1/) an example of what I'm talking about.

**Comment by CLYeo** [comment]
ok thanks, i will check it out 👍
