### ISSUE TITLE
Utilities could be at end of stylesheet

### ISSUE THREAD

**Issue by lentemarton** [KingPixil/wing#59]
Hello,

I've just started working with Wing, which I really enjoy because of its simplicity and good logic! However my suggestion is that utilities may be better at the end of the stylesheet – so that you could better use them to combine with other built-in classes (e.g. for horizontally align cards, etc.).

This way you could spare some more custom css on your projects.

Note: It's not an issue, but a tip – it's good as it is now.

Kind regards,
Márton Lente

**Comment by KingPixil** [comment]
Yeah, that sounds like a good idea! I'll change it right now.

**Comment by lentemarton** [comment]
Thank you! It's just perfect now. :)

________________________________

**Comment by KingPixil** [comment]
Thank you so much! 😄
