### ISSUE TITLE
Bower and CDN?

### ISSUE THREAD

**Issue by CodeBrauer** [KingPixil/wing#6]
Any thoughts on [registering your project to bower](https://bower.io/docs/creating-packages/)?

Also there are some of free CDNs out there so usage could be even easier and/or faster.

- [jsdelivr](https://github.com/jsdelivr/jsdelivr/blob/master/CONTRIBUTING.md)
- [cdnjs](https://github.com/cdnjs/cdnjs/issues/new?title=%5BRequest%5D%20Add%20_library_name_%20&body=**Library%20name%3A**%20%0A**Git%20repository%20url%3A**%0A**npm%20package%20url(optional)%3A**%20%0A**License(s)%3A**%0A**Official%20homepage%3A**%0A**Wanna%20say%20something?%20Leave%20message%20here%3A**%0A%0A=====================%0ANotes%20from%20cdnjs%20maintainer%3A%0APlease%20read%20the%20README.md%20and%20CONTRIBUTING.md%20document%20first.%0A%0AYou%20are%20welcome%20to%20add%20a%20library%20via%20sending%20pull%20request%2C%0Ait%27ll%20be%20faster%20then%20just%20opening%20a%20request%20issue%2C%0Aand%20please%20don%27t%20forget%20to%20read%20the%20guidelines%20for%20contributing%2C%20thanks!!)

**Comment by KingPixil** [comment]
Yes, I will be adding Wing to bower, jsdelivr, and cdnjs. The CDNs take some time to accept people, but adding to Bower will be done soon :smile:

**Comment by KingPixil** [comment]
Alright, so CDNJS kindly allowed me to add Wing. The link is 

**https://cdnjs.cloudflare.com/ajax/libs/wingcss/0.1.4/wing.min.css**

Of course you can also go on http://cdnjs.com and search for "wing".

**Comment by CodeBrauer** [comment]
Awesome. Works fine, thanks for your efforts!

**Comment by KingPixil** [comment]
No problem!

P.S. JSDelivr merged my pull request, it should be up there soon! (After they rebuild it)
