### ISSUE TITLE
Size of default and outline buttons are different

### ISSUE THREAD

**Issue by arecvlohe** [KingPixil/wing#61]
I love the simple styles of Wing. It's such a great and minimal library. I wanted to raise an issue which might be a non-issue. The size of the default button and the outline button are a ~ pixel different in size because the default does not have a border and the outline does. I added a 1.5px size border to the default and now both buttons have close to the same size. Is their difference something intentional? I would love to help with this issue and make a contribution to the project but just want to know if this is really something to fix or this was an intentional design decision.

**Comment by KingPixil** [comment]
I'm super glad you like Wing!

This was not intentional, thanks for bringing it to my attention. If you'd like, you can submit a PR to fix it.

**Comment by arecvlohe** [comment]
I will work on this and get a PR to you today!

**Comment by KingPixil** [comment]
Thank you so much!

**Comment by KingPixil** [comment]
Fixed in #62
