### ISSUE TITLE
CDN not pulling in card styles

### ISSUE THREAD

**Issue by arecvlohe** [KingPixil/wing#63]
I am working here using the CDN (https://unpkg.com/wingcss) for wing.css but the styles for card(s) in not being pulled in. I think this might be related to #60. If you point me in the right direction I can probably pick this up and create a PR.

**Comment by KingPixil** [comment]
This is because cards weren't released in the beta (v1.0.0-beta), but they are going to be released in v1.0.0.

You can't make a PR to fix this, but the best you can do is to use the files in the `dist` folder from this repo (it's the dev version of Wing).

**Comment by sisou** [comment]
Why then has the documentation the link to the unpkg files that do not include cards, but also show how to use cards? :P

**Comment by kbrsh** [comment]
@sisou I'll be honest–the documentation is a bit of a mess right now. It links to the latest development version of Wing but shows how to use the production-ready version (but it still documents the development version).

I'm working on a new documentation website for the new stable version of Wing, and it should be more consistent and clean.
